### ISSUE TITLE
Question regarding usage from LUA

### ISSUE THREAD

**Issue by onlygo** [orangeduck/LuaAutoC#26]
From the documentation, it is not clear if the function registered by luaA_function() is callable from LUA script. Could someone clarify? Thanks.

**Comment by orangeduck** [comment]
Hi @onlygo,

They are not callable from a Lua script directly. For that you need to use something like `lua_register`. You can see a basic example of how to make all registered C functions callable from Lua here: https://github.com/orangeduck/LuaAutoC#quick--dirty-interface

Hope that helps,

- Dan

**Comment by onlygo** [comment]
Thanks Dan. That helps!
