### ISSUE TITLE
luaA_call_entry() does not validate the number of arguments

### ISSUE THREAD

**Issue by fredrikdanielmoller** [orangeduck/LuaAutoC#28]
luaA_call_entry() does not check that it is called with the correct number of arguments.
Expected behaviour is for exception to be raised if it is called with wrong number of arguments.

Example C code:
```
int add_3_integers(int a, int b, int c) {
  return a+b+c;
}
luaA_function(L, add_3_integers, int, int, int, int);
```

Calling this with only one argument from Lua leads to a crash in index2addr() line 69:
`api_check(L, idx != 0 && -idx <= L->top - (ci->func + 1), "invalid index");`

Call stack:
```
index2addr() at lapi.c:69 0x801ec48	
lua_tointegerx() at lapi.c:358 0x801f4c6	
luaA_to_int() at lautoc.c:319 0x802220a	
luaA_to_type() at lautoc.c:218 0x8021f04	
luaA_call_entry() at lautoc.c:1 198 0x8022f34	
luaA_call_name() at lautoc.c:1 259 0x802309e	
```

**Comment by orangeduck** [comment]
Hi @fredrikdanielmoller,

Thanks for the bug report. I've pushed up a new commit to throw an error in this case (d149464). Please tell me if it works for you.

Thanks,

Dan

**Comment by fredrikdanielmoller** [comment]
Thanks a lot!

It almost worked. I just had to do a small change. The following worked:
```
  size_t top = lua_gettop(L);

  if (top < arg_num+3) {
    lua_pop(L, 1);
    lua_pushfstring(L, "luaA_call: Too few arguments to function!");
    lua_error(L);
    return 0;
  }

  if (top > arg_num+3) {
    lua_pop(L, 1);
    lua_pushfstring(L, "luaA_call: Too many arguments to function!");
    lua_error(L);
    return 0;
  }
```

**Comment by fredrikdanielmoller** [comment]
Sorry, I was mistaken. Your code in the commit did work. I was experimenting with some other stuff and that caused the test to fail.

My apology for the confusion.
Regards,
Fredrik

**Comment by orangeduck** [comment]
Great, thanks!
